import { Schema, model, type InferSchemaType } from "mongoose";

const userSchema = new Schema(
  {
    name: { type: String, required: true, trim: true, maxlength: 120 },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true, index: true },
    passwordHash: { type: String, required: true, select: false },
    role: { type: String, enum: ["admin", "user"], required: true, default: "user" },
    language: { type: String, enum: ["en", "ar"], required: true, default: "en" },
    // --- Access control (admin-granted) ---
    // A user may read / ask the AI about a book only if its id is in
    // allowedBookIds OR its category is in allowedCategories. Admins bypass
    // this entirely. Granted by an admin after a paid access request.
    allowedBookIds: { type: [Schema.Types.ObjectId], ref: "Book", default: [] },
    allowedCategories: { type: [String], default: [] },
    // Downloading the raw PDF is a separate, narrower grant than read access:
    // a book must be in allowedBookIds AND here before its file can be
    // downloaded. Defaults closed — admins opt users in book by book.
    allowedDownloadBookIds: { type: [Schema.Types.ObjectId], ref: "Book", default: [] },
    // --- OMP (Open Monograph Press) author link ---
    // Set once the user activates an author account in OMP. The OMP password is
    // generated by us, stored encrypted (never plaintext), and used for SSO login.
    ompUserId: { type: Number },
    ompUsername: { type: String, trim: true },
    ompPasswordEnc: { type: String, select: false },
    ompLinkedAt: { type: Date }
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

export type UserRole = "admin" | "user";
export type UserDocument = InferSchemaType<typeof userSchema> & {
  _id: unknown;
  role: UserRole;
};

export const User = model("User", userSchema);
